eureka:
 instance:
 client:
  service-url:
   defaultZone: http://discovery-server:8761/eureka/
   
spring:
 datasource: 
  url: jdbc:postgresql://localhost:5432/postgres?useSSL=false
  username: postgres
  password: admin
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  properties: 
   hibernate:
    format-sql: true
  